/**
 * The catalog that actually ships.
 *
 * `catalog-refresh.test.ts` covers the refresh SCRIPT against synthetic input.
 * Nothing covered the 1083-location file the installer carries. Those are
 * different things: the script could be correct and the committed artifact
 * stale, hand-edited, or produced by an older mapping — and the artifact is
 * what users see.
 *
 * This matters more than usual here because the catalog is the one part of the
 * product currently showing real data. No source is cleared for collection, so
 * every occupancy figure is empty by design; the map of stations is the
 * application. A wrong row in this file is not a cosmetic defect, it is the
 * product being wrong.
 *
 * These specs recompute rather than restate. The distance to every location is
 * calculated again with the same function the application uses, instead of
 * trusting the `distanceMiles` written into the file.
 */

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it } from 'node:test';

import { distanceMiles } from '../../src/domain/geo.ts';
import { STUDY_AREA_DEFAULTS } from '../../src/domain/thresholds.ts';

const catalogDir = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  '..',
  'resources',
  'catalog',
);

interface Site {
  readonly id: string;
  readonly registryStationId?: string;
  readonly name: string;
  readonly latitude: number;
  readonly longitude: number;
  readonly distanceMiles: number;
  readonly accessCondition: string;
  readonly catalogPortCount: number | null;
  readonly catalogLevel: string | null;
  readonly [key: string]: unknown;
}

function readJson(name: string): Record<string, unknown> {
  return JSON.parse(readFileSync(join(catalogDir, name), 'utf8')) as Record<string, unknown>;
}

const catalog = readJson('mesa-stations.json');
const provenance = readJson('provenance.json');
const sites = catalog['sites'] as Site[];

const centre = {
  latitude: STUDY_AREA_DEFAULTS.centerLatitude,
  longitude: STUDY_AREA_DEFAULTS.centerLongitude,
};

describe('the shipped catalog is a usable file', () => {
  it('parses, declares its format and is not empty', () => {
    assert.equal(catalog['formatVersion'], 1);
    assert.ok(Array.isArray(sites));
    assert.ok(sites.length > 0, 'an empty catalog would render an empty map with no explanation');
  });

  it('gives every location a unique id', () => {
    const ids = new Set(sites.map((site) => site.id));
    assert.equal(ids.size, sites.length, 'duplicate ids would collide in the database');
  });

  it('gives every location a non-empty name', () => {
    const unnamed = sites.filter(
      (site) => typeof site.name !== 'string' || site.name.trim() === '',
    );
    assert.deepEqual(unnamed, [], 'an unnamed pin is not something a user can act on');
  });
});

describe('every shipped location is really inside the study area', () => {
  it('has coordinates in range, and none at the equator', () => {
    for (const site of sites) {
      assert.ok(
        Number.isFinite(site.latitude) && site.latitude >= -90 && site.latitude <= 90,
        `${site.id} has latitude ${site.latitude}`,
      );
      assert.ok(
        Number.isFinite(site.longitude) && site.longitude >= -180 && site.longitude <= 180,
        `${site.id} has longitude ${site.longitude}`,
      );
      // A blank coordinate parsed as 0 lands in the Gulf of Guinea. It is the
      // classic silent import failure, and it would be filtered out by the
      // radius check below anyway — but it is worth failing by name.
      assert.ok(
        !(site.latitude === 0 && site.longitude === 0),
        `${site.id} sits at 0,0 — a blank coordinate read as a number`,
      );
    }
  });

  it('is within the 50-mile radius when the distance is calculated again', () => {
    const outside = sites
      .map((site) => ({
        id: site.id,
        miles: distanceMiles(centre, { latitude: site.latitude, longitude: site.longitude }),
      }))
      .filter((entry) => entry.miles > STUDY_AREA_DEFAULTS.radiusMiles);

    assert.deepEqual(
      outside,
      [],
      'the catalog claims a 50-mile study area; these locations are outside it',
    );
  });

  it('records a distance that matches the recomputed one', () => {
    const drifted = sites
      .map((site) => ({
        id: site.id,
        recorded: site.distanceMiles,
        recomputed: distanceMiles(centre, {
          latitude: site.latitude,
          longitude: site.longitude,
        }),
      }))
      .filter((entry) => Math.abs(entry.recorded - entry.recomputed) > 0.01);

    assert.deepEqual(
      drifted,
      [],
      'a stored distance disagreeing with the coordinates means the file was ' +
        'edited after it was generated, or generated by a different rule',
    );
  });
});

describe('the catalog claims nothing it cannot know', () => {
  it('carries no occupancy, availability or status field', () => {
    // A catalog row is a location that exists. Whether anyone is plugged into
    // it right now is an observation, recorded separately and only when a
    // source is actually read. If those ever merge, the application can show a
    // number nobody measured.
    const forbidden = [
      'available',
      'availablePorts',
      'occupied',
      'occupiedPorts',
      'occupancy',
      'status',
      'inUse',
      'lastSeenStatus',
    ];
    const offenders = sites.flatMap((site) =>
      forbidden.filter((field) => field in site).map((field) => `${site.id}.${field}`),
    );
    assert.deepEqual(offenders, [], 'catalog rows must not carry live-state fields');
  });

  it('never states a port count of zero, which would mean a location with no chargers', () => {
    const zeroed = sites.filter((site) => site.catalogPortCount === 0);
    assert.deepEqual(
      zeroed,
      [],
      'unknown capacity is null; zero is a claim that the site has no ports at all',
    );
  });

  it('keeps port counts as positive whole numbers or null', () => {
    for (const site of sites) {
      if (site.catalogPortCount === null) continue;
      assert.ok(
        Number.isInteger(site.catalogPortCount) && site.catalogPortCount > 0,
        `${site.id} has catalogPortCount ${site.catalogPortCount}`,
      );
    }
  });

  it('uses only the documented charging levels, or null for unknown', () => {
    const allowed = new Set([null, 'level_1', 'level_2', 'dc_fast', 'mixed']);
    const unknown = [
      ...new Set(sites.map((site) => site.catalogLevel).filter((level) => !allowed.has(level))),
    ];
    assert.deepEqual(unknown, [], 'an unrecognised level would not band or filter correctly');
  });

  it('contains only publicly accessible locations', () => {
    // The refresh skips non-public stations; 99 were skipped building this
    // file. A private fleet depot on the map is a location the user cannot
    // drive to.
    const nonPublic = [
      ...new Set(sites.map((site) => site.accessCondition).filter((value) => value !== 'public')),
    ];
    assert.deepEqual(nonPublic, [], 'non-public access conditions present in a public catalog');
  });
});

describe('the catalog can be traced back to its source', () => {
  it('names where the data came from, under what licence, with a file hash', () => {
    for (const field of ['sourceName', 'sourceUrl', 'license', 'attribution', 'fileSha256']) {
      const value = provenance[field];
      assert.ok(
        typeof value === 'string' && value.trim() !== '',
        `provenance.${field} is missing; the catalog would be unattributable`,
      );
    }
    assert.match(
      provenance['fileSha256'] as string,
      /^[0-9a-f]{64}$/,
      'the source hash is what makes a refresh reproducible',
    );
  });

  it('agrees with the catalog about how many locations were accepted', () => {
    const counts = provenance['counts'] as Record<string, number>;
    assert.equal(
      counts['accepted'],
      sites.length,
      'the provenance count and the file disagree, so one of them was not regenerated',
    );
  });

  it('accounts for every row it considered', () => {
    const counts = provenance['counts'] as Record<string, number>;
    const count = (key: string): number => {
      const value = counts[key];
      assert.equal(typeof value, 'number', `provenance.counts.${key} must be a number`);
      return value as number;
    };
    const accountedFor =
      count('accepted') +
      count('skippedNonElectric') +
      count('skippedNonPublic') +
      count('skippedBadCoordinates') +
      count('skippedOutOfRadius');
    assert.equal(
      accountedFor,
      counts['rowsConsidered'],
      'rows went missing between the source file and the catalog without being counted',
    );
  });

  it('was built for the study area the application uses', () => {
    const bounds = provenance['bounds'] as Record<string, number>;
    assert.equal(bounds['centerLatitude'], STUDY_AREA_DEFAULTS.centerLatitude);
    assert.equal(bounds['centerLongitude'], STUDY_AREA_DEFAULTS.centerLongitude);
    assert.equal(
      bounds['radiusMiles'],
      STUDY_AREA_DEFAULTS.radiusMiles,
      'the catalog was filtered to a different radius than the app assumes',
    );
  });
});
